### ISSUE TITLE
Compatibilidad Java 1.5

### ISSUE THREAD

**Issue by dhd0004** [ElevenPaths/latch-sdk-java#10]
En el Readme del API se especifica claramente:
LATCH JAVA SDK
 PREREQUISITES
Java 1.5 or above.
 
El problema es que dentro del código se utiliza en varias ocasiones el método 
```java
java.lang.String.isEmpty
```
El cual solo está disponible a partir de Java 1.6, por lo que puede dar lugar a confusión.

**Comment by jaesga** [comment]
Hola, 

Tienes razón, muchas gracias por el apunte, vamos a actualizar la documentación. 

Un saludo,
Javier.

**Comment by dhd0004** [comment]
Y la posibilidad de mantener la compatibilidad con Java 1.5 cambiando todos los isEmpty() por .lenght==0 ?
En mi caso el entorno de desarrollo es bastante antiguo y necesitamos usar Java 1.5.

**Comment by jaesga** [comment]
El SDK es 'open source', por lo que estamos abiertos a contribuciones de la comunidad. 
Si necesitas la compatibilidad con Java 1.5 puedes enviarnos un pull request sin ningún problema y una vez verificados los cambios los incorporamos a master.

Mas adelante intentaríamos en la medida de lo posible de que las nuevas versiones y funcionalidades del SDK sigan siendo compatibles con Java 1.5.
